INSERT INTO apps (name, categories_id) VALUES ('facebook',1);
INSERT INTO apps (name, categories_id) VALUES ('tweeter',1);
INSERT INTO apps (name, categories_id) VALUES ('scotia',2);
INSERT INTO apps (name, categories_id) VALUES ('TD',2);
INSERT INTO apps (name, categories_id) VALUES ('bambo',3);
INSERT INTO apps (name, categories_id) VALUES ('harvest',3);
INSERT INTO apps (name, categories_id) VALUES ('slack',4);
INSERT INTO apps (name, categories_id) VALUES ('trello',4);
INSERT INTO apps (name, categories_id) VALUES ('google_workspace',4);
